import type { TeamOperatingModel } from "@/lib/operating-models/types";

const GENERAL_KPIS = [
  {
    id: "active_programs",
    name: "Active programs",
    type: "count" as const,
    source: "portfolio" as const,
    portfolioKey: "activeProjects",
    displayLocations: ["team_dashboard", "manager", "executive"] as const,
  },
  {
    id: "open_tasks",
    name: "Open tasks",
    type: "count" as const,
    source: "portfolio" as const,
    portfolioKey: "openTasks",
    displayLocations: ["team_dashboard", "manager"] as const,
  },
  {
    id: "avg_completion_pct",
    name: "Completion",
    type: "percentage" as const,
    source: "portfolio" as const,
    portfolioKey: "avgCompletionPct",
    warnWhen: "low" as const,
    displayLocations: ["team_dashboard", "manager", "executive"] as const,
  },
  {
    id: "ready_for_qa",
    name: "Ready for QA",
    type: "count" as const,
    source: "portfolio" as const,
    portfolioKey: "readyForQa",
    displayLocations: ["team_dashboard", "manager"] as const,
  },
];

export const GENERAL_OPERATING_MODEL: TeamOperatingModel = {
  slug: "general-operations",
  label: "General Operations",
  description: "Default operating model — Work Package / Phase / Task with core progress KPIs.",
  hierarchyLabels: {
    workPackage: "Work Package",
    workPackageShort: "Package",
    workPackagePlural: "Work Packages",
    phase: "Phase",
    phaseShort: "Phase",
    phasePlural: "Phases",
    task: "Task",
    taskPlural: "Tasks",
  },
  structureMode: "custom",
  projectTypes: ["custom", "research", "board"],
  defaultProjectType: "custom",
  taskTypes: ["general", "deliverable", "review"],
  trackingFields: ["hours", "files", "qa"],
  kpis: GENERAL_KPIS.map((k) => ({ ...k, displayLocations: [...k.displayLocations] })),
  forecastRules: {
    defaultMinutesPerUnit: 60,
    productiveHoursPerDay: 6,
    capacityThresholdPct: 85,
    dueDateMethod: "forecast",
  },
  taskDefaults: {
    qaRequired: false,
    filesRequired: false,
    showWorkstreamPicker: true,
    showYearPicker: true,
  },
  isGeneral: true,
};

export const SERVICE_INFORMATION_MODEL: TeamOperatingModel = {
  slug: "service-information",
  label: "Service Information",
  description: "Manufacturer / Year / Task — documents, files, QA, and corrections.",
  hierarchyLabels: {
    workPackage: "Manufacturer",
    workPackageShort: "Manufacturer",
    workPackagePlural: "Manufacturers",
    phase: "Year",
    phaseShort: "Year",
    phasePlural: "Years",
    task: "Task",
    taskPlural: "Tasks",
  },
  structureMode: "by_manufacturer",
  projectTypes: ["si_corrections", "special_functions"],
  defaultProjectType: "si_corrections",
  taskTypes: ["document", "correction", "review", "qa"],
  trackingFields: ["documents", "files", "qa", "corrections", "hours"],
  kpis: [
    {
      id: "documents_completed",
      name: "Documents completed",
      type: "count",
      source: "manual",
      displayLocations: ["team_dashboard", "manager", "report"],
    },
    {
      id: "qa_pass_rate",
      name: "QA pass rate",
      type: "percentage",
      source: "portfolio",
      portfolioKey: "readyForQa",
      warnWhen: "low",
      displayLocations: ["team_dashboard", "manager"],
    },
    {
      id: "correction_rate",
      name: "Corrections",
      type: "count",
      source: "manual",
      displayLocations: ["team_dashboard", "report"],
    },
    {
      id: "open_tasks",
      name: "Open tasks",
      type: "count",
      source: "portfolio",
      portfolioKey: "openTasks",
      displayLocations: ["team_dashboard"],
    },
  ],
  forecastRules: {
    defaultMinutesPerUnit: 45,
    productiveHoursPerDay: 6,
    complexityMultipliers: { simple: 0.8, standard: 1, complex: 1.4 },
    capacityThresholdPct: 90,
    dueDateMethod: "forecast",
    defaultUnit: "files",
  },
  taskDefaults: {
    qaRequired: true,
    filesRequired: true,
    showWorkstreamPicker: true,
    showYearPicker: true,
  },
};

export const ADVANCED_PROJECTS_MODEL: TeamOperatingModel = {
  slug: "advanced-projects",
  label: "Advanced Projects",
  description:
    "Zach's team workspace — projects and tasks by category, hours-based tracking, daily summaries with next actions, no QA/upload gates.",
  hierarchyLabels: {
    workPackage: "Workstream",
    workPackageShort: "Workstream",
    workPackagePlural: "Workstreams",
    phase: "Milestone",
    phaseShort: "Milestone",
    phasePlural: "Milestones",
    task: "Task",
    taskPlural: "Tasks",
  },
  structureMode: "by_workstream",
  projectTypes: [
    "development",
    "research",
    "debugging",
    "feature_addition",
    "maintenance",
    "testing",
    "documentation",
    "reporting",
    "automation",
    "custom",
  ],
  defaultProjectType: "development",
  taskTypes: [
    "feature",
    "bug",
    "deployment",
    "automation",
    "research",
    "testing",
    "documentation",
    "maintenance",
    "other",
  ],
  trackingFields: ["hours", "features", "bugs", "deployments"],
  kpis: [
    {
      id: "features_delivered",
      name: "Features delivered",
      type: "count",
      source: "manual",
      displayLocations: ["team_dashboard", "manager"],
    },
    {
      id: "bugs_closed",
      name: "Bugs closed",
      type: "count",
      source: "manual",
      displayLocations: ["team_dashboard"],
    },
    {
      id: "avg_health_score",
      name: "Avg health score",
      type: "percentage",
      source: "intelligence",
      portfolioKey: "avgHealthScore",
      warnWhen: "low",
      displayLocations: ["team_dashboard", "manager", "executive"],
    },
    {
      id: "at_risk_programs",
      name: "At-risk programs",
      type: "count",
      source: "portfolio",
      portfolioKey: "projectsAtRisk",
      warnWhen: "high",
      displayLocations: ["team_dashboard", "executive"],
    },
  ],
  forecastRules: {
    defaultMinutesPerUnit: 90,
    productiveHoursPerDay: 6,
    complexityMultipliers: { simple: 0.7, standard: 1, complex: 1.6 },
    capacityThresholdPct: 80,
    dueDateMethod: "forecast",
  },
  taskDefaults: {
    qaRequired: false,
    filesRequired: false,
    showWorkstreamPicker: true,
    showYearPicker: false,
  },
  contentChecksEnabled: false,
  uploadGate: { enabled: false, minTimedMinutes: 30 },
  wrapUpFields: [
    {
      id: "progress",
      label: "Work performed & progress made",
      placeholder: "What moved forward today?",
    },
    { id: "next_action", label: "Next planned action", placeholder: "What's first tomorrow?" },
    {
      id: "estimated_completion",
      label: "Estimated completion / remaining time",
      placeholder: "e.g. Friday, or ~6 hours left",
    },
    {
      id: "additional_notes",
      label: "Links or additional notes",
      placeholder: "Repo links, PRs, anything else",
    },
  ],
  workspace: { showActiveProjectsPanel: true, overdueFirst: true, notifyManagerOnEdits: true },
  managerUpdate: {
    enabled: true,
    fields: [
      { id: "contributions", label: "Manager contributions" },
      { id: "team_support", label: "Team support provided" },
      { id: "project_decisions", label: "Project decisions" },
      { id: "risks_identified", label: "Risks identified" },
      { id: "blockers_resolved", label: "Blockers resolved" },
      { id: "leadership_communication", label: "Leadership communication" },
      { id: "resource_needs", label: "Resource needs" },
      { id: "team_accomplishments", label: "Team accomplishments" },
      { id: "next_week_priorities", label: "Priorities for the following week" },
    ],
  },
  weeklyUpdates: {
    enabled: true,
    fields: [
      { id: "work_completed", label: "Work Completed This Week" },
      { id: "time_expectation", label: "Time Expectation for Completion" },
      { id: "errors_issues", label: "Errors or Issues Encountered" },
      { id: "next_steps", label: "Next Steps" },
    ],
    opens: { day: 4, hour: 17 },
    due: { day: 5, hour: 15 },
  },
};

export const ID3_VALIDATION_MODEL: TeamOperatingModel = {
  slug: "id3-validation",
  label: "ID³ Validation",
  description: "Dataset / Validation Batch / Task — records, accuracy, exceptions.",
  hierarchyLabels: {
    workPackage: "Dataset",
    workPackageShort: "Dataset",
    workPackagePlural: "Datasets",
    phase: "Validation Batch",
    phaseShort: "Batch",
    phasePlural: "Validation Batches",
    task: "Task",
    taskPlural: "Tasks",
  },
  structureMode: "custom",
  projectTypes: ["id3_validation", "custom"],
  defaultProjectType: "id3_validation",
  taskTypes: ["validation", "exception_review", "signoff"],
  trackingFields: ["records", "accuracy", "qa", "hours"],
  kpis: [
    {
      id: "records_validated",
      name: "Records validated",
      type: "count",
      source: "manual",
      displayLocations: ["team_dashboard", "manager", "report"],
    },
    {
      id: "accuracy_pct",
      name: "Accuracy %",
      type: "percentage",
      source: "manual",
      target: 98,
      warningThreshold: 95,
      warnWhen: "low",
      displayLocations: ["team_dashboard", "executive", "report"],
    },
    {
      id: "exceptions_found",
      name: "Exceptions found",
      type: "count",
      source: "manual",
      warnWhen: "high",
      displayLocations: ["team_dashboard", "report"],
    },
    {
      id: "validation_coverage",
      name: "Validation coverage",
      type: "percentage",
      source: "manual",
      displayLocations: ["team_dashboard", "manager"],
    },
  ],
  forecastRules: {
    defaultMinutesPerUnit: 2,
    productiveHoursPerDay: 7,
    capacityThresholdPct: 85,
    dueDateMethod: "forecast",
    defaultUnit: "records",
  },
  taskDefaults: {
    qaRequired: true,
    filesRequired: false,
    showWorkstreamPicker: true,
    showYearPicker: false,
  },
};

export const TRAINING_MODEL: TeamOperatingModel = {
  slug: "training",
  label: "Training",
  description: "Training Module / Phase / Task — completion, certification, sign-off.",
  hierarchyLabels: {
    workPackage: "Training Module",
    workPackageShort: "Module",
    workPackagePlural: "Training Modules",
    phase: "Training Phase",
    phaseShort: "Phase",
    phasePlural: "Training Phases",
    task: "Task",
    taskPlural: "Tasks",
  },
  structureMode: "by_year_phase",
  projectTypes: ["training", "custom"],
  defaultProjectType: "training",
  taskTypes: ["lesson", "assessment", "certification", "review"],
  trackingFields: ["hours", "qa", "files"],
  kpis: [
    {
      id: "training_completion",
      name: "Training completion",
      type: "percentage",
      source: "portfolio",
      portfolioKey: "avgCompletionPct",
      warnWhen: "low",
      displayLocations: ["team_dashboard", "manager"],
    },
    {
      id: "employees_trained",
      name: "Employees trained",
      type: "count",
      source: "manual",
      displayLocations: ["team_dashboard", "report"],
    },
    {
      id: "certification_status",
      name: "Certification status",
      type: "status",
      source: "manual",
      displayLocations: ["team_dashboard", "manager"],
    },
  ],
  forecastRules: {
    defaultMinutesPerUnit: 30,
    productiveHoursPerDay: 6,
    dueDateMethod: "calendar",
  },
  taskDefaults: {
    qaRequired: true,
    filesRequired: true,
    showWorkstreamPicker: true,
    showYearPicker: true,
  },
};

export const DEFAULT_OPERATING_MODEL_PRESETS: TeamOperatingModel[] = [
  GENERAL_OPERATING_MODEL,
  SERVICE_INFORMATION_MODEL,
  ADVANCED_PROJECTS_MODEL,
  ID3_VALIDATION_MODEL,
  TRAINING_MODEL,
];

/** Infer operating model from legacy project_type when no team model is assigned. */
export const PROJECT_TYPE_MODEL_SLUG: Record<string, string> = {
  si_corrections: "service-information",
  special_functions: "service-information",
  adas: "advanced-projects",
  research: "advanced-projects",
  development: "advanced-projects",
  debugging: "advanced-projects",
  feature_addition: "advanced-projects",
  maintenance: "advanced-projects",
  testing: "advanced-projects",
  documentation: "advanced-projects",
  reporting: "advanced-projects",
  automation: "advanced-projects",
  id3_validation: "id3-validation",
  training: "training",
  board: "general-operations",
  custom: "general-operations",
};
