"use client";

import Link from "next/link";
import { Badge } from "@/components/ui/badge";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import type { ValidationCenterKpis, ValidationRunView } from "@/lib/validation-center/types";
import { validationPath } from "@/lib/validation-center/nav";
import { Download, ExternalLink } from "lucide-react";

export function ValidationReportsView({
  kpis,
  runs,
}: {
  kpis: ValidationCenterKpis;
  runs: ValidationRunView[];
}) {
  const completed = runs.filter((r) => r.status === "completed");

  return (
    <div className="space-y-8">
      <section>
        <h3 className="text-sm font-semibold mb-1">Compliance trend</h3>
        <p className="text-xs text-muted-foreground mb-3">
          Historical compliance from completed validation runs.
        </p>
        {kpis.trendPoints.length === 0 ? (
          <p className="text-sm text-muted-foreground py-6 text-center">
            No trend data yet.{" "}
            <Link href={validationPath("/new")} className="text-primary hover:underline">
              Run a validation
            </Link>{" "}
            to start building history.
          </p>
        ) : (
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Date</TableHead>
                <TableHead>Manufacturer</TableHead>
                <TableHead className="text-right">Compliance</TableHead>
                <TableHead className="text-right">Run</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {[...kpis.trendPoints].reverse().map((point) => (
                <TableRow key={point.runId}>
                  <TableCell>{point.date}</TableCell>
                  <TableCell>{point.manufacturer ?? "—"}</TableCell>
                  <TableCell className="text-right font-medium tabular-nums">
                    {point.complianceRate}%
                  </TableCell>
                  <TableCell className="text-right">
                    <Link
                      href={validationPath(`/runs/${point.runId}`)}
                      className="inline-flex items-center gap-1 text-sm text-primary hover:underline"
                    >
                      View
                      <ExternalLink className="h-3 w-3" />
                    </Link>
                  </TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        )}
      </section>

      <section>
        <h3 className="text-sm font-semibold mb-1">Run exports</h3>
        <p className="text-xs text-muted-foreground mb-3">
          Download workbooks and PDFs generated by the validation engine.
        </p>
        {completed.length === 0 ? (
          <p className="text-sm text-muted-foreground">No completed runs with exports.</p>
        ) : (
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Run</TableHead>
                <TableHead>Manufacturer</TableHead>
                <TableHead className="text-right">Compliance</TableHead>
                <TableHead>Artifacts</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {completed.slice(0, 25).map((run) => {
                const workbook = run.files.find((f) => f.role === "output_workbook");
                const pdf = run.files.find((f) => f.role === "output_pdf");
                return (
                  <TableRow key={run.id}>
                    <TableCell>
                      <Link
                        href={validationPath(`/runs/${run.id}`)}
                        className="font-medium text-primary hover:underline truncate block max-w-xs"
                      >
                        {run.title ?? run.id.slice(0, 8)}
                      </Link>
                    </TableCell>
                    <TableCell>{run.manufacturer ?? "—"}</TableCell>
                    <TableCell className="text-right tabular-nums">
                      {run.compliance_rate != null ? `${run.compliance_rate}%` : "—"}
                    </TableCell>
                    <TableCell>
                      <div className="flex flex-wrap gap-2">
                        {workbook && (
                          <a
                            href={`/api/validation/files/${workbook.id}`}
                            className="inline-flex items-center gap-1 text-xs text-primary hover:underline"
                          >
                            <Download className="h-3 w-3" />
                            Workbook
                          </a>
                        )}
                        {pdf && (
                          <a
                            href={`/api/validation/files/${pdf.id}`}
                            className="inline-flex items-center gap-1 text-xs text-primary hover:underline"
                          >
                            <Download className="h-3 w-3" />
                            PDF
                          </a>
                        )}
                        {!workbook && !pdf && (
                          <Badge variant="outline" className="text-xs">
                            No files
                          </Badge>
                        )}
                      </div>
                    </TableCell>
                  </TableRow>
                );
              })}
            </TableBody>
          </Table>
        )}
      </section>

      <section className="grid gap-3 sm:grid-cols-4 text-sm">
        <SummaryCard label="Library accuracy" value={kpis.libraryAccuracyPct != null ? `${kpis.libraryAccuracyPct}%` : "—"} />
        <SummaryCard label="Audit pass rate" value={kpis.auditPassRate != null ? `${kpis.auditPassRate}%` : "—"} />
        <SummaryCard label="Open findings" value={kpis.openFindings} href={validationPath("/findings")} />
        <SummaryCard label="Resolved" value={kpis.resolvedFindings} href={validationPath("/corrections")} />
      </section>
    </div>
  );
}

function SummaryCard({
  label,
  value,
  href,
}: {
  label: string;
  value: string | number;
  href?: string;
}) {
  const inner = (
    <div className="rounded-lg border bg-muted/20 px-4 py-3 h-full">
      <p className="text-xs text-muted-foreground">{label}</p>
      <p className="text-xl font-semibold tabular-nums mt-1">{value}</p>
    </div>
  );
  if (href) {
    return (
      <Link href={href} className="hover:ring-1 hover:ring-primary/30 rounded-lg block">
        {inner}
      </Link>
    );
  }
  return inner;
}
