import type { EnterpriseProjectTemplate } from "./enterprise-types";

const NOW = "2026-01-01T00:00:00.000Z";

function task(
  key: string,
  title: string,
  sort: number,
  opts?: Partial<EnterpriseProjectTemplate["tasks"][0]>
) {
  return {
    key,
    title,
    sort_order: sort,
    status: "not_started" as const,
    priority: "medium" as const,
    estimated_document_count: 20,
    complexity_level: "standard" as const,
    estimated_hours: 4,
    requires_qa: true,
    requires_files: true,
    ...opts,
  };
}

export const BUILTIN_ENTERPRISE_TEMPLATES: EnterpriseProjectTemplate[] = [
  {
    id: "standard_production",
    label: "Standard Production Project",
    description: "Daily production work, processing queues, and normal operational delivery.",
    useCases: ["Daily production work", "Processing queues", "Normal operational work"],
    category: "Production",
    projectType: "production",
    builtin: true,
    archived: false,
    createdAt: NOW,
    updatedAt: NOW,
    departmentIds: [],
    defaultPriority: "medium",
    defaultComplexity: "standard",
    defaultEstimatedDocuments: 100,
    forecastingEnabled: true,
    qaEnabled: true,
    fileUploadsRequired: true,
    wrapUpsEnabled: true,
    workflowManufacturerName: "Production Pipeline",
    tasks: [
      task("intake", "Intake", 1, { estimated_document_count: 10, estimated_hours: 2 }),
      task("processing", "Processing", 2, { estimated_document_count: 40, estimated_hours: 8 }),
      task("qa_review", "QA Review", 3, { estimated_document_count: 10, estimated_hours: 2, requires_files: false }),
      task("corrections", "Corrections", 4, { estimated_document_count: 15, estimated_hours: 3 }),
      task("final_completion", "Final Completion", 5, { estimated_document_count: 25, estimated_hours: 4, priority: "high" }),
    ],
    metrics: { projectsCreated: 0, lastUsedAt: null },
  },
  {
    id: "audit_validation",
    label: "Audit & Validation Project",
    description: "Library audits, data validation, compliance reviews, and SI audits.",
    useCases: ["Library audits", "Data validation", "Compliance reviews", "SI audits"],
    category: "Audit",
    projectType: "audit",
    builtin: true,
    archived: false,
    createdAt: NOW,
    updatedAt: NOW,
    departmentIds: [],
    defaultPriority: "high",
    defaultComplexity: "complex",
    defaultEstimatedDocuments: 120,
    forecastingEnabled: true,
    qaEnabled: true,
    fileUploadsRequired: true,
    wrapUpsEnabled: true,
    workflowManufacturerName: "Audit Workflow",
    tasks: [
      task("scope_review", "Scope Review", 1, { estimated_document_count: 15, complexity_level: "standard" }),
      task("data_collection", "Data Collection", 2, { estimated_document_count: 30, estimated_hours: 6 }),
      task("validation", "Validation", 3, { estimated_document_count: 25, estimated_hours: 5 }),
      task("findings_review", "Findings Review", 4, { estimated_document_count: 20, estimated_hours: 4 }),
      task("qa_review", "QA Review", 5, { estimated_document_count: 10, estimated_hours: 2 }),
      task("final_report", "Final Report", 6, { estimated_document_count: 20, estimated_hours: 4, priority: "high" }),
    ],
    metrics: { projectsCreated: 0, lastUsedAt: null },
  },
  {
    id: "research_investigation",
    label: "Research & Investigation Project",
    description: "Manufacturer investigations, root cause analysis, and special requests.",
    useCases: ["Manufacturer investigations", "Root cause analysis", "Special requests", "Data gathering"],
    category: "Research",
    projectType: "research",
    builtin: true,
    archived: false,
    createdAt: NOW,
    updatedAt: NOW,
    departmentIds: [],
    defaultPriority: "medium",
    defaultComplexity: "complex",
    defaultEstimatedDocuments: 80,
    forecastingEnabled: true,
    qaEnabled: true,
    fileUploadsRequired: true,
    wrapUpsEnabled: true,
    workflowManufacturerName: "Investigation Track",
    tasks: [
      task("intake", "Intake", 1, { estimated_document_count: 8 }),
      task("research", "Research", 2, { estimated_document_count: 25, estimated_hours: 6 }),
      task("evidence_collection", "Evidence Collection", 3, { estimated_document_count: 20, estimated_hours: 5 }),
      task("analysis", "Analysis", 4, { estimated_document_count: 15, estimated_hours: 4 }),
      task("findings", "Findings", 5, { estimated_document_count: 12, estimated_hours: 3 }),
      task("final_review", "Final Review", 6, { estimated_document_count: 10, estimated_hours: 2, priority: "high" }),
    ],
    metrics: { projectsCreated: 0, lastUsedAt: null },
  },
  {
    id: "training_onboarding",
    label: "Training & Onboarding Project",
    description: "New employee onboarding, cross training, and process training programs.",
    useCases: ["New employees", "Cross training", "Process training"],
    category: "Training",
    projectType: "training",
    builtin: true,
    archived: false,
    createdAt: NOW,
    updatedAt: NOW,
    departmentIds: [],
    defaultPriority: "medium",
    defaultComplexity: "simple",
    defaultEstimatedDocuments: 50,
    forecastingEnabled: true,
    qaEnabled: true,
    fileUploadsRequired: false,
    wrapUpsEnabled: true,
    workflowManufacturerName: "Training Program",
    tasks: [
      task("training_materials", "Training Materials", 1, { estimated_document_count: 15, requires_qa: false, requires_files: false }),
      task("knowledge_review", "Knowledge Review", 2, { estimated_document_count: 10, requires_qa: false }),
      task("practice_work", "Practice Work", 3, { estimated_document_count: 20, estimated_hours: 6 }),
      task("supervisor_review", "Supervisor Review", 4, { estimated_document_count: 5, requires_files: false }),
      task("certification", "Certification", 5, { estimated_document_count: 5, priority: "high", requires_files: false }),
    ],
    metrics: { projectsCreated: 0, lastUsedAt: null },
  },
  {
    id: "corrective_action",
    label: "Corrective Action / Improvement Project",
    description: "Quality improvement, process corrections, and department initiatives.",
    useCases: ["Quality improvement", "Process corrections", "Department initiatives", "Performance improvement"],
    category: "Improvement",
    projectType: "corrective_action",
    builtin: true,
    archived: false,
    createdAt: NOW,
    updatedAt: NOW,
    departmentIds: [],
    defaultPriority: "high",
    defaultComplexity: "standard",
    defaultEstimatedDocuments: 90,
    forecastingEnabled: true,
    qaEnabled: true,
    fileUploadsRequired: true,
    wrapUpsEnabled: true,
    workflowManufacturerName: "Improvement Initiative",
    tasks: [
      task("issue_identification", "Issue Identification", 1, { estimated_document_count: 10 }),
      task("root_cause_analysis", "Root Cause Analysis", 2, { estimated_document_count: 15, estimated_hours: 4 }),
      task("corrective_plan", "Corrective Plan", 3, { estimated_document_count: 15, estimated_hours: 3 }),
      task("implementation", "Implementation", 4, { estimated_document_count: 25, estimated_hours: 6 }),
      task("validation", "Validation", 5, { estimated_document_count: 15, estimated_hours: 3 }),
      task("final_review", "Final Review", 6, { estimated_document_count: 10, estimated_hours: 2, priority: "high" }),
    ],
    metrics: { projectsCreated: 0, lastUsedAt: null },
  },
];
